export const projectDetails = [
  {
    id: "quote-generator",
    title: "Quote Generator",
    github: "https://github.com/saimahmedkhan/quote-generator",
    vercel: "https://quote-generator.vercel.app",
    weakness: "Currently uses static quotes; lacks API integration.",
    enhancementsToMake: ["Integrate quote API", "add tweet feature."],
    description: "This is an Amazing Project",
    techStack: ["React", "CSS"],
    conceptsUsed: ["State", "Event Handling", "Conditional Rendering"],
  },
  {
    id: "ebook-store",
    title: "Ebook Store",
    github: "https://github.com/saimahmedkhan/ebook-store",
    vercel: "https://ebook-store.vercel.app",
    weakness: "No real payment or backend support.",
    description: "This is an Amazing Project",
    enhancementsToMake: [
      "Add payment gateway",
      "filter/sort books",
      "connect to database.",
    ],
    techStack: ["React", "Tailwind", "React Router"],
    conceptsUsed: ["Routing", "Component Design", "Props"],
  },
  {
    id: "simple-calculator",
    title: "Simple Calculator",
    github: "https://github.com/saimahmedkhan/simple-calculator",
    vercel: "https://simple-calculator.vercel.app",
    weakness: "No keyboard support, minimal styling.",
    enhancementsToMake: [
      "Add keyboard support",
      "improve styling",
      "add history feature.",
    ],
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "This is an Amazing Project",
    conceptsUsed: ["DOM Manipulation", "Events", "Functions"],
  },
  {
    id: "tip-calculator",
    title: "Tip Calculator",
    github: "https://github.com/saimahmedkhan/tip-calculator",
    vercel: "https://tip-calculator.vercel.app",
    weakness: "No validation on input fields.",
    enhancementsToMake: ["Add input validation ", "animated UI."],
    techStack: ["React", "CSS Modules"],
    description: "This is an Amazing Project",
    conceptsUsed: ["useState", "Input Handling", "Form Validation"],
  },
  {
    id: "markdown-previewer",
    title: "Markdown Previewer",
    github: "https://github.com/saimahmedkhan/markdown-previewer",
    vercel: "https://markdown-previewer.vercel.app",
    weakness: "Limited markdown support.",
    enhancementsToMake: ["Support full markdown spec", "add dark mode toggle."],
    techStack: ["React", "Marked.js"],
    description: "This is an Amazing Project",
    conceptsUsed: ["Third-party Libraries", "Live Preview", "State Syncing"],
  },
  {
    id: "countdown-timer",
    title: "Countdown Timer",
    description: "This is an Amazing Project",
    github: "https://github.com/saimahmedkhan/countdown-timer",
    vercel: "https://countdown-timer.vercel.app",
    weakness: "Time input isn’t intuitive, no sound/alarm at end.",
    enhancementsToMake: ["Improve input UI", " add notification/alarm."],
    techStack: ["React", "CSS"],
    conceptsUsed: ["Timers", "useEffect", "Cleanup Functions"],
  },
  {
    id: "smart-clock",
    title: "Digital Smart Clock",
    description: "This is an Amazing Project",
    github: "https://github.com/saimahmedkhan/smart-clock",
    vercel: "https://smart-clock.vercel.app",
    weakness: "Just shows time, no world clock or theme.",
    enhancementsToMake: ["Add themes", "world clock toggle", "analog mode."],
    techStack: ["React", "Date API", "TailwindCSS"],
    conceptsUsed: ["Time Manipulation", "Reusable Components", "Live Updates"],
  },
];
