export const projectDetails = [
  {
    id: "quote-generator",
    title: "Quote Generator",
    image: "/assets/Quote Generator.png",
    video: "/assets/Quote Generator Live Preview.webm",
    github:
      "https://github.com/Saimahmed78/10-Days-10-JS-Projects-Series/tree/main/Random-Quote-Generator",
    vercel: "https://quotegenerator-amber.vercel.app/",
    weakness: "Currently uses static quotes; lacks API integration.",
    enhancementsToMake: ["Integrate quote API", "add tweet feature."],
    description: "This is an Amazing Project",
    techStack: ["HTML", "CSS", "JS"],
    conceptsUsed: ["State", "Event Handling", "Conditional Rendering"],
  },
  {
    id: "ebook-store",
    title: "Ebook Store",
    image: "/assets/Ebook Store.png",
    github: "https://github.com/Saimahmed78/Ebook-Store",
    vercel: "https://ebook-store-sable.vercel.app/",
    weakness: "No real payment or backend support.",
    description: "This is an Amazing Project",
    enhancementsToMake: [
      "Add payment gateway",
      "filter/sort books",
      "connect to database.",
    ],
    techStack: ["React", "Tailwind", "React Router"],
    conceptsUsed: ["Routing", "Component Design", "Props"],
  },
  {
    id: "simple-calculator",
    title: "Simple Calculator",
    image: "/assets/Simple Calculator.png",
    github: "https://github.com/Saimahmed78/10-Days-10-JS-Projects-Series/tree/main/Simple-Calculator",
    vercel: "https://simplecalculator-wine.vercel.app/",
    weakness: "No keyboard support, minimal styling.",
    enhancementsToMake: [
      "Add keyboard support",
      "improve styling",
      "add history feature.",
    ],
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "This is an Amazing Project",
    conceptsUsed: ["DOM Manipulation", "Events", "Functions"],
  },
  {
    id: "tip-calculator",
    title: "Tip Calculator",
    image: "/assets/Tip Calculator.png",
    github: "https://github.com/Saimahmed78/10-Days-10-JS-Projects-Series/tree/main/Tip-Calculator",
    vercel: "https://tip-calulator.vercel.app/",
    weakness: "No validation on input fields.",
    enhancementsToMake: ["Add input validation ", "animated UI."],
    techStack: ["React", "CSS Modules"],
    description: "This is an Amazing Project",
    conceptsUsed: ["useState", "Input Handling", "Form Validation"],
  },
  {
    id: "markdown-previewer",
    title: "Markdown Previewer",
    image: "/assets/MarkDown previwer.png",
    github: "https://github.com/Saimahmed78/Markdown-Previewer",
    vercel: "https://markdown-previewer-jade-seven.vercel.app/",
    weakness: "Limited markdown support.",
    enhancementsToMake: ["Support full markdown spec", "add dark mode toggle."],
    techStack: ["React", "Marked.js"],
    description: "This is an Amazing Project",
    conceptsUsed: ["Third-party Libraries", "Live Preview", "State Syncing"],
  },
  {
    id: "countdown-timer",
    title: "Countdown Timer",
    image: "/assets/countdown timer.png",
    description: "This is an Amazing Project",
    github: "https://github.com/Saimahmed78/10-Days-10-JS-Projects-Series/tree/main/Digital%20Stop%20Watch",
    vercel: "https://digitalstopwatch-livid.vercel.app/",
    weakness: "Time input isn’t intuitive, no sound/alarm at end.",
    enhancementsToMake: ["Improve input UI", " add notification/alarm."],
    techStack: ["React", "CSS"],
    conceptsUsed: ["Timers", "useEffect", "Cleanup Functions"],
  },
  {
    id: "smart-clock",
    title: "Digital Smart Clock",
    image: "/assets/SmarkClock.png",
    description: "This is an Amazing Project",
    github: "https://github.com/Saimahmed78/10-Days-10-JS-Projects-Series/tree/main/Digital%20Clock",
    vercel: "https://digitalclock-psi.vercel.app/",
    weakness: "Just shows time, no world clock or theme.",
    enhancementsToMake: ["Add themes", "world clock toggle", "analog mode."],
    techStack: ["React", "Date API", "TailwindCSS"],
    conceptsUsed: ["Time Manipulation", "Reusable Components", "Live Updates"],
  },
];
